# CI/CD Pipeline for the Notification Service
name: CI - Notification Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'notification-service/**'
      - '.github/workflows/notification-service-ci.yml'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./notification-service

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
      # - name: Run Tests
      #   run: npm test
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./notification-service
          file: ./notification-service/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notification-service:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_SERVER_HOST }}
          username: ${{ secrets.PROD_SERVER_USERNAME }}
          key: ${{ secrets.PROD_SERVER_SSH_KEY }}
          script: |
            set -e
            export PROJ_DIR=/home/ubuntu/studyonic
            
            if [ ! -d "$PROJ_DIR/.git" ]; then
              echo "Cloning repository for the first time"
              git clone https://github.com/${{ github.repository }}.git /tmp/repo-temp
              mkdir -p $PROJ_DIR
              mv /tmp/repo-temp/* $PROJ_DIR/
              mv /tmp/repo-temp/.git* $PROJ_DIR/
              rm -rf /tmp/repo-temp
            fi
            
            cd $PROJ_DIR
            
            echo "Repository exists, pulling latest changes"
            git reset --hard
            git pull origin main

            docker ps -aq | xargs -r docker stop || true
            docker ps -aq | xargs -r docker rm || true
            docker network ls -q | xargs -r docker network rm || true

            yes | docker system prune -a --volumes || true

            echo "Logging in to Docker Hub"
            echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
            
            echo "Starting application stack with latest images"
            docker compose up -d --build --force-recreate --pull=always --remove-orphans
            
            echo "Pruning old Docker images"
            docker image prune -af
            
            echo "Deployment successful! Listing running containers:"
            docker ps